### ISSUE TITLE
Diff option -d always returns nothing

### ISSUE THREAD

**Issue by chrisolsen** [sqs/goreturns#28] opened 2016-10-18 16:11 UTC
This issue is in regards to vscode no longer adding/removing imports on save. An additional option was added to override the use of `goreturns -d` and fallback to `goreturns -w`, which gets things working for me again.

The initial issue: https://github.com/Microsoft/vscode-go/issues/520

I am using:
- Go 1.6
- vscode 1.6.1
- vscode go plugin 0.6.45
- windows 10 Home

**Comment by sqs** [comment] 2016-10-18 16:56
Thanks for filing. Is that option an effective workaround? What fixes/changes need to be made to goreturns?

**Comment by shurcooL** [comment] 2016-10-18 18:53
@chrisolsen, do you have `diff` command installed on Windows 10 home?

`-d` flag relies on it to perform the diff. See [here](https://github.com/sqs/goreturns/blob/6b4ef8abebcf672cfd4bcad23744d47e8f203725/goreturns.go#L200). If you don't have it, it would fail to work.

**Comment by shurcooL** [comment] 2016-10-18 18:59
If my theory above about `diff` being the issue here, then...

> What fixes/changes need to be made to goreturns?

Easy: It should check that `diff` binary exists, and exit with error if `-d` flag is used but `diff` isn't available. Especially since it ignores the exit code from running the command. This wouldn't fix the problem, but at least it'd make it visible.

Hard: Rewrite `diff` in pure Go and avoid an external dependency. :)

**Comment by chrisolsen** [comment] 2016-10-18 19:00
I do have diff.
```
C:\Users\chris>diff -v
diff - GNU diffutils version 2.7

C:\Users\chris>vim test.go  // see test file

C:\Users\chris>goreturns -d test.go
diff test.go gofmt/test.go    // only output
```

test.go
```
package testme

func main() {
	fmt.Println("testing...")  // should add `import "fmt"`
}
```

**Comment by shurcooL** [comment] 2016-10-18 19:10
If it's printing "diff test.go gofmt/test.go", that means it got to here:

https://github.com/sqs/goreturns/blob/6b4ef8abebcf672cfd4bcad23744d47e8f203725/goreturns.go#L120

So `diff` did run. I'd suggest adding some debug printfs to the code to see what's really going on. It could be that your `diff` command produces unexpected output when given `-u` flag, or something else.

**Comment by chrisolsen** [comment] 2016-10-19 16:13
`goimports` does return the same output.

**Comment by marpaia** [comment] 2016-10-27 15:08
For what it's worth, I also came across this issue through my usage of VS Code as referenced in https://github.com/Microsoft/vscode-go/issues/520.

**Comment by ramya-rao-a** [comment] 2017-02-05 02:53
@shurcooL Any new ideas or updates on this one? The Go extension for VS Code depends on the diff output from `goreturns`.

**Comment by shurcooL** [comment] 2017-02-05 03:03
I don't see evidence in this issue that there's a problem in code. I suspect it was some specific environment issue on that person's computer. According to https://github.com/sqs/goreturns/issues/28#issuecomment-254862010, they said it happens with `goimports` too.

I tested both `goimports` and `goreturns`, `-d` option works as expected for me on macOS.

I would suggest closing this issue and suggesting to anyone who actually runs into this problem to make a new issue with more information and reproduce steps.

**Comment by chrisolsen** [comment] 2017-02-05 03:41
I guess I should chime in :) Early this week I had to re-install Windows and noticed that the problem was no longer causing issues.  I assumed a fix was made on your guy's side.

**Comment by shurcooL** [comment] 2017-02-05 03:45
Great! I think that confirms it was an environment issue. The only changed merged into `goreturns` since this issue was opened on Oct 18, 2016 was a new feature. See https://github.com/sqs/goreturns/commits/master.

**Comment by ramya-rao-a** [comment] 2017-02-05 06:22
It is interesting that 3 to 4 people would have had the same environment issue :)
But yes, it doesnt look like the problem is with `goreturns`.

@chrisolsen can you close this issue then?

**Closed** 2017-02-05 07:09 UTC
